name: Destroy

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
env:
  AWS_REGION: us-east-1

jobs:
  Destroy_ECS:
    name: Destroy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: PWD
        run: |
          ls -al
          pwd

      - name: Terraform Destroy ECS service
        run: |
          terraform -chdir=deployment init
          terraform -chdir=deployment destroy -auto-approve

  Infrastructure_Destroy:
    name: Infrastructure_Destroy
    needs: [Destroy_ECS]
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Destroy Infrastructure
        run: |
          terraform -chdir=iac init
          terraform -chdir=iac destroy -auto-approve
